name: Build new version

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    build-extension:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Remove extra files and especific git folders
              run: rm -rf README.md LICENSE .git .github

            - name: Get actual date for version name.
              id: actual-date
              run: echo "DATE=$(date +'%Y.%-m.%d')" >> $GITHUB_OUTPUT

            - name: Replace version name in manifest.json
              run: sed -i 's/12345/${{ steps.actual-date.outputs.DATE }}/g' manifest.json

            - name: Create extension's zip files
              run: zip -r autolingo .

            - name: Create release
              id: create-release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: ./autolingo.zip
                  draft: true
                  generateReleaseNotes: true
                  prerelease: true
                  tag: ${{ steps.actual-date.outputs.DATE }}
                  artifactContentType: application/zip
